### ISSUE TITLE
I am having trouble compiling the hello example

### ISSUE THREAD

**Issue by pbrumm** [zombodb/pgx#16]
I am using 20.04 ubuntu with stock rustc.    I have set my path for cargo and have pg_config in path.  

```
[12.3] [stdout] make[4]: Leaving directory '/home/pbrumm/pg_bitquery/target/postgresql-12.3/src/common'
[12.3] [stdout] make[3]: Leaving directory '/home/pbrumm/pg_bitquery/target/postgresql-12.3/src/interfaces/libpq'
[12.3] [stdout] make[2]: Leaving directory '/home/pbrumm/pg_bitquery/target/postgresql-12.3/src/test/isolation'
[12.3] [stdout] make[1]: Leaving directory '/home/pbrumm/pg_bitquery/target/postgresql-12.3/src'
[12.3] [stderr] + cd /home/pbrumm/pg_bitquery/target/postgresql-12.3
[12.3] [stderr] + '[' '!' -f config.status ']'
[12.3] [stderr] + ./configure --prefix=/home/pbrumm/pg_bitquery/target/postgresql-12.3/pgx-install --without-readline --without-zlib -with-pgport=8812
[12.3] [stderr] + '[' '!' -f /home/pbrumm/pg_bitquery/target/postgresql-12.3/pgx-install/bin/postgres ']'
[12.3] [stderr] + make -j 5
[12.3] [stderr] gcc: fatal error: cannot read spec file ‘./specs’: Is a directory
[12.3] [stderr] compilation terminated.
[12.3] [stderr] make[2]: *** [<builtin>: specparse.o] Error 1
[12.3] [stderr] make[2]: *** Waiting for unfinished jobs....
[12.3] [stderr] gcc: fatal error: cannot read spec file ‘./specs’: Is a directory
[12.3] [stderr] compilation terminated.
[12.3] [stderr] make[2]: *** [<builtin>: isolationtester.o] Error 1
[12.3] [stderr] gcc: fatal error: cannot read spec file ‘./specs’: Is a directory
[12.3] [stderr] compilation terminated.
[12.3] [stderr] make[2]: *** [<builtin>: isolation_main.o] Error 1
[12.3] [stderr] make[1]: *** [Makefile:42: all-test/isolation-recurse] Error 2
[12.3] [stderr] make: *** [GNUmakefile:11: all-src-recurse] Error 2
[12.3] [stderr] + exit 1
[12.3] /----------------------------------------

thread '<unnamed>' panicked at 'failed to compile Postgres v12.3', /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.0.4/build.rs:287:14
stack backtrace:
   0:     0x55f78a846b73 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4ef1f84901fa8edc
   1:     0x55f78a8640dd - core::fmt::write::h026b5c0fa015f11c
   2:     0x55f78a845cb5 - std::io::Write::write_fmt::hc77e135d55d2160d
   3:     0x55f78a849e1e - std::panicking::default_hook::{{closure}}::h7a1ebe73b27c35f6
   4:     0x55f78a849b30 - std::panicking::default_hook::hc9a55f38c57244a0
   5:     0x55f78a84a4fb - std::panicking::rust_panic_with_hook::hd3ad4a665e641fa7
   6:     0x55f78a84a0ae - rust_begin_unwind
   7:     0x55f78a849ff0 - std::panicking::begin_panic_fmt::h1e4a1c904d7eb2f7
   8:     0x55f78a017493 - build_script_build::compile_postgres::h1f97e74dfceb7e2e
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.0.4/build.rs:287
   9:     0x55f78a01490f - build_script_build::main::{{closure}}::he465a0cd0e1a51f9
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.0.4/build.rs:113
  10:     0x55f78a012313 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut::h26278ceea995277f
                               at /usr/src/rustc-1.41.0/src/libcore/ops/function.rs:252
  11:     0x55f78a02b8ed - core::iter::traits::iterator::Iterator::for_each::call::{{closure}}::h40e7d576a6bc1bf1
                               at /usr/src/rustc-1.41.0/src/libcore/iter/traits/iterator.rs:629
  12:     0x55f78a02add8 - core::iter::traits::iterator::Iterator::fold::ok::{{closure}}::h719d08f59d55fcf9
                               at /usr/src/rustc-1.41.0/src/libcore/iter/traits/iterator.rs:1829
  13:     0x55f78a00f107 - core::iter::traits::iterator::Iterator::try_fold::hc8816c4cac676472
                               at /usr/src/rustc-1.41.0/src/libcore/iter/traits/iterator.rs:1710
  14:     0x55f78a00b86e - core::iter::traits::iterator::Iterator::fold::h35c4f86164ba1d00
                               at /usr/src/rustc-1.41.0/src/libcore/iter/traits/iterator.rs:1832
  15:     0x55f78a00cc0c - core::iter::traits::iterator::Iterator::for_each::h8a8376ab0220bbea
                               at /usr/src/rustc-1.41.0/src/libcore/iter/traits/iterator.rs:632
  16:     0x55f789fee94e - <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter::hb6eebacc52f79cb4
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.3.1/src/iter/for_each.rs:55
  17:     0x55f789ffe2be - rayon::iter::plumbing::Producer::fold_with::h81cbb8a60d7242c3
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.3.1/src/iter/plumbing/mod.rs:110
  18:     0x55f78a02e02f - rayon::iter::plumbing::bridge_producer_consumer::helper::h75a6fdd60f34eccf
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.3.1/src/iter/plumbing/mod.rs:438
  19:     0x55f78a02e2da - rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}::he6593c93a132dea9
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.3.1/src/iter/plumbing/mod.rs:427
  20:     0x55f78a01a42f - rayon_core::join::join_context::call_b::{{closure}}::h6a55407af6384f2d
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/join/mod.rs:130
  21:     0x55f789fe2512 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::call::{{closure}}::h0e2cf0656bfd05e7
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/job.rs:113
  22:     0x55f78a019670 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h808679ff31855677
                               at /usr/src/rustc-1.41.0/src/libstd/panic.rs:318
  23:     0x55f78a01b02e - std::panicking::try::do_call::hc883de5c948bd719
                               at /usr/src/rustc-1.41.0/src/libstd/panicking.rs:292
  24:     0x55f78a84e48a - __rust_maybe_catch_panic
  25:     0x55f78a01ad2e - std::panicking::try::h650df14c946883d1
                               at /usr/src/rustc-1.41.0/src/libstd/panicking.rs:270
  26:     0x55f78a01a792 - std::panic::catch_unwind::h85d1a16d067113e1
                               at /usr/src/rustc-1.41.0/src/libstd/panic.rs:394
  27:     0x55f789feea6f - rayon_core::unwind::halt_unwinding::h80be1878277c04e9
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/unwind.rs:17
  28:     0x55f789fe21ab - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hce1d24a18d402950
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/job.rs:119
  29:     0x55f78a1d1f66 - rayon_core::job::JobRef::execute::h5ba2780576e5d2ec
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/job.rs:59
  30:     0x55f78a1cbb2d - rayon_core::registry::WorkerThread::execute::hd016764618062486
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:685
  31:     0x55f78a1cb836 - rayon_core::registry::WorkerThread::wait_until_cold::hd9e954d412c2fa04
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:669
  32:     0x55f78a1cb156 - rayon_core::registry::WorkerThread::wait_until::h440fd0891a627775
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:643
  33:     0x55f78a1cc366 - rayon_core::registry::main_loop::h69a5991763cd151a
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:763
  34:     0x55f78a1c9060 - rayon_core::registry::ThreadBuilder::run::hcae4539176983f8c
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:56
  35:     0x55f78a1c96a1 - <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}::h609d2e53f7cf2984
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:101
  36:     0x55f78a1df060 - std::sys_common::backtrace::__rust_begin_short_backtrace::h702555aa88d17f61
                               at /usr/src/rustc-1.41.0/src/libstd/sys_common/backtrace.rs:136
  37:     0x55f78a1e6111 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h57f8e203e05eec92
                               at /usr/src/rustc-1.41.0/src/libstd/thread/mod.rs:469
  38:     0x55f78a1e4c23 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h49e6b785dc47c84f
                               at /usr/src/rustc-1.41.0/src/libstd/panic.rs:318
  39:     0x55f78a1ef653 - std::panicking::try::do_call::h13479e341e364396
                               at /usr/src/rustc-1.41.0/src/libstd/panicking.rs:292
  40:     0x55f78a84e48a - __rust_maybe_catch_panic
  41:     0x55f78a1ef548 - std::panicking::try::hec248c78942e54c1
                               at /usr/src/rustc-1.41.0/src/libstd/panicking.rs:270
  42:     0x55f78a1e5323 - std::panic::catch_unwind::he93cda27e90d61c4
                               at /usr/src/rustc-1.41.0/src/libstd/panic.rs:394
  43:     0x55f78a1e5ef6 - std::thread::Builder::spawn_unchecked::{{closure}}::haea9673371700eec
                               at /usr/src/rustc-1.41.0/src/libstd/thread/mod.rs:468
  44:     0x55f78a1d8934 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc7dd0c4f9b1ef688
                               at /usr/src/rustc-1.41.0/src/libcore/ops/function.rs:232
  45:     0x55f78a83ebcf - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2f9577dd894cb305
  46:     0x55f78a845e10 - std::sys_common::thread::start_thread::h05cb3555d2d68d0a
  47:     0x55f78a83cae6 - std::sys::unix::thread::Thread::new::thread_start::ha2762cba1ba415cc
  48:     0x7efe0d1c9609 - start_thread
  49:     0x7efe0d0d5103 - __clone
  50:                0x0 - <unknown>

Error: Os { code: 101, kind: Other, message: "Network is unreachable" }

```

the same thing happens for 10 and 11

```
[10.13] [stderr] + cd /home/pbrumm/pg_bitquery/target/postgresql-10.13
[10.13] [stderr] + '[' '!' -f config.status ']'
[10.13] [stderr] + ./configure --prefix=/home/pbrumm/pg_bitquery/target/postgresql-10.13/pgx-install --without-readline --without-zlib -with-pgport=8810
[10.13] [stderr] + '[' '!' -f /home/pbrumm/pg_bitquery/target/postgresql-10.13/pgx-install/bin/postgres ']'
[10.13] [stderr] + make -j 5
[10.13] [stderr] gcc: fatal error: cannot read spec file ‘./specs’: Is a directory
[10.13] [stderr] compilation terminated.
[10.13] [stderr] make[2]: *** [<builtin>: specparse.o] Error 1
[10.13] [stderr] make[2]: *** Waiting for unfinished jobs....
[10.13] [stderr] gcc: fatal error: cannot read spec file ‘./specs’: Is a directory
[10.13] [stderr] compilation terminated.
[10.13] [stderr] make[2]: *** [<builtin>: isolationtester.o] Error 1
[10.13] [stderr] gcc: fatal error: cannot read spec file ‘./specs’: Is a directory
[10.13] [stderr] compilation terminated.
[10.13] [stderr] make[2]: *** [<builtin>: isolation_main.o] Error 1
[10.13] [stderr] make[1]: *** [Makefile:38: all-test/isolation-recurse] Error 2
[10.13] [stderr] make: *** [GNUmakefile:11: all-src-recurse] Error 2
[10.13] [stderr] + exit 1
[10.13] /----------------------------------------

thread '<unnamed>' panicked at 'failed to compile Postgres v10.13', /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.0.4/build.rs:287:14
stack backtrace:
   0:     0x55f78a846b73 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4ef1f84901fa8edc
   1:     0x55f78a8640dd - core::fmt::write::h026b5c0fa015f11c
   2:     0x55f78a845cb5 - std::io::Write::write_fmt::hc77e135d55d2160d
   3:     0x55f78a849e1e - std::panicking::default_hook::{{closure}}::h7a1ebe73b27c35f6
   4:     0x55f78a849b30 - std::panicking::default_hook::hc9a55f38c57244a0
   5:     0x55f78a84a4fb - std::panicking::rust_panic_with_hook::hd3ad4a665e641fa7
   6:     0x55f78a84a0ae - rust_begin_unwind
   7:     0x55f78a849ff0 - std::panicking::begin_panic_fmt::h1e4a1c904d7eb2f7
   8:     0x55f78a017493 - build_script_build::compile_postgres::h1f97e74dfceb7e2e
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.0.4/build.rs:287
   9:     0x55f78a01490f - build_script_build::main::{{closure}}::he465a0cd0e1a51f9
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.0.4/build.rs:113
  10:     0x55f78a012313 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut::h26278ceea995277f
                               at /usr/src/rustc-1.41.0/src/libcore/ops/function.rs:252
  11:     0x55f78a02b8ed - core::iter::traits::iterator::Iterator::for_each::call::{{closure}}::h40e7d576a6bc1bf1
                               at /usr/src/rustc-1.41.0/src/libcore/iter/traits/iterator.rs:629
  12:     0x55f78a02add8 - core::iter::traits::iterator::Iterator::fold::ok::{{closure}}::h719d08f59d55fcf9
                               at /usr/src/rustc-1.41.0/src/libcore/iter/traits/iterator.rs:1829
  13:     0x55f78a00f107 - core::iter::traits::iterator::Iterator::try_fold::hc8816c4cac676472
                               at /usr/src/rustc-1.41.0/src/libcore/iter/traits/iterator.rs:1710
  14:     0x55f78a00b86e - core::iter::traits::iterator::Iterator::fold::h35c4f86164ba1d00
                               at /usr/src/rustc-1.41.0/src/libcore/iter/traits/iterator.rs:1832
  15:     0x55f78a00cc0c - core::iter::traits::iterator::Iterator::for_each::h8a8376ab0220bbea
                               at /usr/src/rustc-1.41.0/src/libcore/iter/traits/iterator.rs:632
  16:     0x55f789fee94e - <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter::hb6eebacc52f79cb4
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.3.1/src/iter/for_each.rs:55
  17:     0x55f789ffe2be - rayon::iter::plumbing::Producer::fold_with::h81cbb8a60d7242c3
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.3.1/src/iter/plumbing/mod.rs:110
  18:     0x55f78a02e02f - rayon::iter::plumbing::bridge_producer_consumer::helper::h75a6fdd60f34eccf
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.3.1/src/iter/plumbing/mod.rs:438
  19:     0x55f78a02e1fa - rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}::h3ce23f8d37b0e4a5
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.3.1/src/iter/plumbing/mod.rs:418
  20:     0x55f78a01a375 - rayon_core::join::join_context::call_a::{{closure}}::hb91a4ef0b0f9bf9d
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/join/mod.rs:125
  21:     0x55f78a0196b0 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd1a1d085437d6e4f
                               at /usr/src/rustc-1.41.0/src/libstd/panic.rs:318
  22:     0x55f78a01afbe - std::panicking::try::do_call::h77f9652e57fc9b39
                               at /usr/src/rustc-1.41.0/src/libstd/panicking.rs:292
  23:     0x55f78a84e48a - __rust_maybe_catch_panic
  24:     0x55f78a01abae - std::panicking::try::h3898e88ac07e3391
                               at /usr/src/rustc-1.41.0/src/libstd/panicking.rs:270
  25:     0x55f78a01a7e2 - std::panic::catch_unwind::h8882b725d6414bec
                               at /usr/src/rustc-1.41.0/src/libstd/panic.rs:394
  26:     0x55f789feeaef - rayon_core::unwind::halt_unwinding::h8b3384713762fba9
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/unwind.rs:17
  27:     0x55f78a019ad3 - rayon_core::join::join_context::{{closure}}::h165048404ccfcd5f
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/join/mod.rs:146
  28:     0x55f789fdd986 - rayon_core::registry::Registry::in_worker_cold::{{closure}}::{{closure}}::hfccec1de986c74d6
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:447
  29:     0x55f789fe2564 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::call::{{closure}}::h42b2840058076055
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/job.rs:113
  30:     0x55f78a0196f2 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::heb7c37d19b9d872e
                               at /usr/src/rustc-1.41.0/src/libstd/panic.rs:318
  31:     0x55f78a01b0a1 - std::panicking::try::do_call::he11e4e307c5567e8
                               at /usr/src/rustc-1.41.0/src/libstd/panicking.rs:292
  32:     0x55f78a84e48a - __rust_maybe_catch_panic
  33:     0x55f78a01aeae - std::panicking::try::hfd371ad52def9ad1
                               at /usr/src/rustc-1.41.0/src/libstd/panicking.rs:270
  34:     0x55f78a01a742 - std::panic::catch_unwind::h70f35ea9fbf395fd
                               at /usr/src/rustc-1.41.0/src/libstd/panic.rs:394
  35:     0x55f789feeb72 - rayon_core::unwind::halt_unwinding::hf49ebaba9a21e4f7
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/unwind.rs:17
  36:     0x55f789fe1e05 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::ha2bfc31e6e3e9730
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/job.rs:119
  37:     0x55f78a1d1f66 - rayon_core::job::JobRef::execute::h5ba2780576e5d2ec
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/job.rs:59
  38:     0x55f78a1cbb2d - rayon_core::registry::WorkerThread::execute::hd016764618062486
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:685
  39:     0x55f78a1cb836 - rayon_core::registry::WorkerThread::wait_until_cold::hd9e954d412c2fa04
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:669
  40:     0x55f78a1cb156 - rayon_core::registry::WorkerThread::wait_until::h440fd0891a627775
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:643
  41:     0x55f78a1cc366 - rayon_core::registry::main_loop::h69a5991763cd151a
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:763
  42:     0x55f78a1c9060 - rayon_core::registry::ThreadBuilder::run::hcae4539176983f8c
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:56
  43:     0x55f78a1c96a1 - <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}::h609d2e53f7cf2984
                               at /home/pbrumm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.7.1/src/registry.rs:101
  44:     0x55f78a1df060 - std::sys_common::backtrace::__rust_begin_short_backtrace::h702555aa88d17f61
                               at /usr/src/rustc-1.41.0/src/libstd/sys_common/backtrace.rs:136
  45:     0x55f78a1e6111 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h57f8e203e05eec92
                               at /usr/src/rustc-1.41.0/src/libstd/thread/mod.rs:469
  46:     0x55f78a1e4c23 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h49e6b785dc47c84f
                               at /usr/src/rustc-1.41.0/src/libstd/panic.rs:318
  47:     0x55f78a1ef653 - std::panicking::try::do_call::h13479e341e364396
                               at /usr/src/rustc-1.41.0/src/libstd/panicking.rs:292
  48:     0x55f78a84e48a - __rust_maybe_catch_panic
  49:     0x55f78a1ef548 - std::panicking::try::hec248c78942e54c1
                               at /usr/src/rustc-1.41.0/src/libstd/panicking.rs:270
  50:     0x55f78a1e5323 - std::panic::catch_unwind::he93cda27e90d61c4
                               at /usr/src/rustc-1.41.0/src/libstd/panic.rs:394
  51:     0x55f78a1e5ef6 - std::thread::Builder::spawn_unchecked::{{closure}}::haea9673371700eec
                               at /usr/src/rustc-1.41.0/src/libstd/thread/mod.rs:468
  52:     0x55f78a1d8934 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc7dd0c4f9b1ef688
                               at /usr/src/rustc-1.41.0/src/libcore/ops/function.rs:232
  53:     0x55f78a83ebcf - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2f9577dd894cb305
  54:     0x55f78a845e10 - std::sys_common::thread::start_thread::h05cb3555d2d68d0a
  55:     0x55f78a83cae6 - std::sys::unix::thread::Thread::new::thread_start::ha2762cba1ba415cc
  56:     0x7efe0d1c9609 - start_thread
  57:     0x7efe0d0d5103 - __clone
  58:                0x0 - <unknown>
```

Should I be looking for missing dependencies in the postgres compile phase,  or is this something in pbx?
I did see a warning around Flex so I installed that.

**Comment by pbrumm** [comment]
I found this link for postgresql dependencies and made sure I had all of them.

[compile and install postgres](https://wiki.postgresql.org/wiki/Compile_and_Install_from_source_code )

but the same issue above shows up after cargo clean and reattempt.

**Comment by eeeebbbbrrrr** [comment]
I assume you were running “cargo pgx install”

Can you please do:  cargo clean && PGX_BUILD_FLAGS=“-vv” cargo pgx install

and then attach that entire output here?  You might want to 2>&1 > output.log that command.  

It’s odd to me that you’ve got compilation problems with Postgres. Anything that might be considered non-standard about your setup?

**Comment by eeeebbbbrrrr** [comment]
(as an aside, I'm working diligently on #14, which will make this process easier -- but I'd like to understand your problem compiling Postgres)

**Comment by pbrumm** [comment]
it is a 19.10 upgrade to 20.04.   I am also running with pg 11 running,  but it should be pretty stock.   
[output2.log](https://github.com/zombodb/pgx/files/4933492/output2.log)
[output1.log](https://github.com/zombodb/pgx/files/4933493/output1.log)

**Comment by eeeebbbbrrrr** [comment]
This is weird.  I've never seen this before, but, this issue elsewhere on GitHub seems related.  Here's the comment that describes what's wrong and how to fix:

https://github.com/raphlinus/pulldown-cmark/issues/122#issuecomment-364948741

That comments talks about `LIBRARY_PATH` not containing the "current directory", and indicates that that also means the envvar cannot begin or end with a colon (`:`).

Looks like yours does:

```
cat output2.log| grep -e "^LIBRARY_PATH" 
LIBRARY_PATH=/opt/intel/opencl-1.2-6.4.0.37/lib64/:
```

So... try unsetting `LIBRARY_PATH` before running `cargo pgx install`, or otherwise figure out why it's set to what it is, and fix it at its source:  

`LIBRARY_PATH= cargo pgx install` (note the space after the `=`)

I do have a "denylist" of environment variables I don't pass through to the spawned shell that builds Postgres, so I suppose I could add this one to that list.

**Comment by eeeebbbbrrrr** [comment]
yeah, I can recreate your problem, even with the new stuff I'm working on as part of #14:

` LIBRARY_PATH=: cargo pgx init`

That fails with the same error:

```
...
gcc: fatal error: cannot read spec file ‘./specs’: Is a directory
...
```

I'm adding LIBRARY_PATH to the denylist for the new stuff.  In the mean time, you'll have to manage that environment variable yourself.

**Comment by pbrumm** [comment]
great find on the colon.   I had set that up as an env variable but now have it wrapped up in an if condition.
[output1.log](https://github.com/zombodb/pgx/files/4934025/output1.log)
[output2.log](https://github.com/zombodb/pgx/files/4934026/output2.log)



I had to install clang as well.   

It still looks like I have an issue around llvm-config 

I have uploaded new results.   I will try to set that llvm-config path and try again

**Comment by pbrumm** [comment]
I installed llvm and am retrying

**Comment by pbrumm** [comment]
I am getting this now 
```

[shim for PG v11] [stderr] Makefile:12: warning: ignoring old recipe for target 'libpgx-cshim-11.a'
[shim for PG v11] [stderr] pgx-cshim.c: In function ‘pgx_deconstruct_row_type’:
[shim for PG v11] [stderr] pgx-cshim.c:104:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
[shim for PG v11] [stderr]   104 |     Datum *cols = palloc(natts * sizeof(Datum));
[shim for PG v11] [stderr]       |     ^~~~~
[shim for PG v11] /----------------------------------------
```
[output2.log](https://github.com/zombodb/pgx/files/4934056/output2.log)

that isn't the full output.  I will rerun and upload the full

**Comment by eeeebbbbrrrr** [comment]
hmm, looks like your only problem is you're missing `rustfmt`:

```
Failed to run rustfmt: Cannot find binary path (non-fatal, continuing)
Failed to run rustfmt: Cannot find binary path (non-fatal, continuing)
Failed to run rustfmt: Cannot find binary path (non-fatal, continuing)
```

I don't know why you'd had to install clang tho.  I can that locally.  Should have just needed the gcc toolchain.

Regarding the `llvm-config` thing -- is that just warnings from cargo?  If so, that's no big deal.

Thanks for pushing through all this.  It's helping me to make `pgx` better for everyone!

**Comment by pbrumm** [comment]
I ran 

`crate install rustfmt`

and I was able to get through the bulid.      It is failing on the copying the control file and probably the .so

also does it attempt the other versions after 12?   or is there a way to just have it run the 11 so I can copy the files over manually?

my concern is that it is overwriting the .so and stuff for each postgres version.

Thanks for all your help.   this is the first rust thing that has intrigued me enough to install it.    I can't wait to play around with this.

**Comment by eeeebbbbrrrr** [comment]
`cargo pgx install` only installs to the Postgres instance dictated by the `pg_config` that's on your path.  And will need write permissions to `$(pg_config --pkglibdir)` and `$(pg_config --sharedir)` in order for `cargo pgx install` to complete successfully.

Sounds like you're right there at the end.

Soon as I get #15 wrapped up, all this stuff will be a ton easier as pgx will (or can) manage private PG installations for you.

**Comment by eeeebbbbrrrr** [comment]
As a followup, we kinda missed the boat with this `cargo pgx` subcommand.  There's only two of us here at ZomboDB and we developed the tool to fit our daily workflows.  Plus, the (very) small group of people that had pre-release access to pgx are also very experienced writing PG extensions.  That helped a ton for proving out pgx itself, but not so much for the tooling around it.  Heck, even in the C world, there's no tooling around PG extensions, except for "make".  So we're doing new things in a new language.

That said, I'm busting my butt this week to get things sorted out, so hopefully by Monday this small part of our world will be a better place.

Thanks for hanging in there!

**Comment by eeeebbbbrrrr** [comment]
> hmm, looks like your only problem is you're missing rustfmt:

also, I guess I should use the `rustfmt` crate instead of shelling out to the CLI.  I'll add that to my TODO list over on #14, right now.

**Comment by pbrumm** [comment]
I got through the setup.  and have the extension running!

I am using the stock postgres on ubuntu and figuring out that copy was a pain.   It may be easier to just create an output folder and instructions on where to copy based on pg_config.      or just a simple script that I can run with sudo.     distributing this to a production box seems like a challenge with the current process.

```
sudo cp target/debug/libpg_bitquery.so /usr/lib/postgresql/11/lib/pg_bitquery.so
sudo cp pg_bitquery.control /usr/share/postgresql/11/extension/
```
I would love to hear your thoughts at some point around an upgrade process.  so I can copy the files over and then run the 

`psql>ALTER EXTENSION pg_bitquery UPDATE;`

or something like that.   the current process of just overwriting causes my console to crash.    Once I reconnect everything is fine but that wouldn't work on production.

Thanks for all your help and all the awesome innovation.  I am super excited to start playing around now.

**Comment by eeeebbbbrrrr** [comment]
If you read through the outline in issue #14, you'll see where we're going.  Regarding "distributing to a production box", that's where `cargo pgx package` (from #14) will come into play.

`cargo pgx install` does a little more than just copy the `.so`.  It also copies the `.control` file, and generates the extension `.sql` file, in place.

Regarding the `ALTER EXTENSION ... UPDATE;` command -- yeah.  That's actually the reason I made https://github.com/zombodb/postgres-parser.  I plan on creating a schema "diff" tool, and using that with `cargo pgx` to generate the upgrade .sql scripts that Postgres wants, in order to upgrade from one extension version to the next.  That's going to be a project on its own, but I need to do in order for me to properly maintain the rust port of https://github.com/zombodb/zomobodb.

Anyways, I should have #14 wrapped up today -- famous last words.

**Comment by eeeebbbbrrrr** [comment]
> I had to install clang as well.

Wanted to circle back here...

On my Ubuntu 20.04 box, I uninstalled clang/llvm, and re-ran through the whole process as described by #14 (which I'm about to publish as v0.0.7, btw), and it all worked fine.  That box now only has gcc 9.3.0.

So I'm not sure why you needed clang?

Regardless, I'm going to close this issue as soon as I get 0.0.7 tagged and published to crates.io.  And again, I appreciate your perseverance with this.

**Comment by eeeebbbbrrrr** [comment]
please try with v0.0.7 and let us know if you've got any problems there
