### ISSUE TITLE
Passing test fails after recompiling without any meaningful changes. 

### ISSUE THREAD

**Issue by osawyerr** [zombodb/pgx#357]
Passing test fails after recompiling without any meaningful changes. Killing the postgres process and restarting doesn't fix the issue. Only resolved after restarting machine:

To recreate: 

- Create a pgx project 
- Run tests with: cargo pgx test pg14
- Result: Test passes
- Make small change to test (any change that triggers a compile)

```rust
#[pg_extern]
fn hello_mantis() -> &'static str {
    let foo = "Hello, mantis";
    println!("Foo");
    foo
}
```

- Rerun:  cargo pgx test pg14
- Result: Test fails

Attached verbose logs:

```
olo@MacBook-Pro mantis % cargo pgx test pg14    
"cargo" "test" "--lib" "--features" " pg14 pg_test" "--no-default-features"
    Finished test [unoptimized + debuginfo] target(s) in 0.06s
     Running unittests (target/debug/deps/mantis-efb2d53201b90ee2)

running 1 test
building extension with features `pg14 pg_test`
"cargo" "build" "--lib" "--features" "pg14 pg_test" "--no-default-features"
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s

installing extension
     Copying control file to `/Users/olo/.pgx/14.1/pgx-install/share/postgresql/extension/mantis.control`
     Copying shared library to `/Users/olo/.pgx/14.1/pgx-install/lib/postgresql/mantis.so`
    Building SQL generator with features `pg14 pg_test`
"cargo" "build" "--bin" "sql-generator" "--features" "pg14 pg_test" "--no-default-features"
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
 Discovering SQL entities
  Discovered 3 SQL entities: 1 schemas (1 unique), 2 functions, 0 types, 0 enums, 0 sqls, 0 ords, 0 hashes
running SQL generator with features `pg14 pg_test`
"cargo" "run" "--bin" "sql-generator" "--features" "pg14 pg_test" "--no-default-features" "--" "--sql" "/Users/olo/.pgx/14.1/pgx-install/share/postgresql/extension/mantis--1.0.sql"
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/sql-generator --sql /Users/olo/.pgx/14.1/pgx-install/share/postgresql/extension/mantis--1.0.sql`
     Copying extension schema file to `/Users/olo/.pgx/14.1/pgx-install/share/postgresql/extension/mantis--1.0.sql`
    Finished installing mantis
test tests::pg_test_hello_mantis ... FAILED

failures:

---- tests::pg_test_hello_mantis stdout ----
installing extension
"/Users/olo/.pgx/14.1/pgx-install/bin/postmaster" "-D" "/Users/olo/Documents/Source/Repo/mantis/target/pgx-test-data-14" "-h" "localhost" "-p" "32214"
pid=3176
PostgreSQL 14.1 on aarch64-apple-darwin21.1.0, compiled by Apple clang version 12.0.5 (clang-1205.0.22.9), 64-bit
[2022-01-02 14:55:54.422 GMT] [3176] [61d1bcfa.c68]: LOG:  starting PostgreSQL 14.1 on aarch64-apple-darwin21.1.0, compiled by Apple clang version 12.0.5 (clang-1205.0.22.9), 64-bit
[2022-01-02 14:55:54.423 GMT] [3176] [61d1bcfa.c68]: LOG:  listening on IPv6 address "::1", port 32214
[2022-01-02 14:55:54.423 GMT] [3176] [61d1bcfa.c68]: LOG:  listening on IPv4 address "127.0.0.1", port 32214
[2022-01-02 14:55:54.423 GMT] [3176] [61d1bcfa.c68]: LOG:  listening on Unix socket "/Users/olo/.pgx/.s.PGSQL.32214"
[2022-01-02 14:55:54.425 GMT] [3177] [61d1bcfa.c69]: LOG:  database system was interrupted while in recovery at 2022-01-02 14:55:30 GMT
[2022-01-02 14:55:54.425 GMT] [3177] [61d1bcfa.c69]: HINT:  This probably means that some data is corrupted and you will have to use the last backup for recovery.
[2022-01-02 14:55:54.446 GMT] [3177] [61d1bcfa.c69]: LOG:  database system was not properly shut down; automatic recovery in progress
[2022-01-02 14:55:54.446 GMT] [3177] [61d1bcfa.c69]: LOG:  redo starts at 0/16CA618
[2022-01-02 14:55:54.447 GMT] [3177] [61d1bcfa.c69]: LOG:  invalid record length at 0/16CA710: wanted 24, got 0
[2022-01-02 14:55:54.447 GMT] [3177] [61d1bcfa.c69]: LOG:  redo done at 0/16CA6C8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
     Creating database pgx_tests
thread 'tests::pg_test_hello_mantis' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Closed, cause: None }', /Users/olo/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-tests-0.2.6/src/framework.rs:486:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1298:23
   4: pgx_tests::framework::create_extension
             at /Users/olo/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-tests-0.2.6/src/framework.rs:481:5
   5: pgx_tests::framework::initialize_test_framework
             at /Users/olo/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-tests-0.2.6/src/framework.rs:173:9
   6: pgx_tests::framework::run_test
             at /Users/olo/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-tests-0.2.6/src/framework.rs:57:41
   7: mantis::tests::pg_test_hello_mantis
             at ./src/lib.rs:18:5
   8: mantis::tests::pg_test_hello_mantis::{{closure}}
             at ./src/lib.rs:18:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', /Users/olo/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-tests-0.2.6/src/framework.rs:392:64
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1298:23
   4: pgx_tests::framework::monitor_pg::{{closure}}
             at /Users/olo/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-tests-0.2.6/src/framework.rs:392:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    tests::pg_test_hello_mantis

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.04s

Stopping Postgres

error: test failed, to rerun pass '--lib'
      [error] cargo pgx test failed with status = Some(101)
```

**Comment by osawyerr** [comment]
@Hoverbear confirmed this is fixed by https://github.com/zombodb/pgx/pull/333. Closing Issue.
